<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.pPyP_uR' shared service.

return $this->privates['.service_locator.pPyP_uR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService.php', true],
], [
    'categorieRepository' => 'App\\Repository\\CategorieRepository',
]);
