<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.zqACQ6g' shared service.

return $this->privates['.service_locator.zqACQ6g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ClientController::delete' => ['privates', '.service_locator.G3Dsh9s', 'get_ServiceLocator_G3Dsh9sService.php', true],
    'App\\Controller\\ClientController::edit' => ['privates', '.service_locator.G3Dsh9s', 'get_ServiceLocator_G3Dsh9sService.php', true],
    'App\\Controller\\ClientController::index' => ['privates', '.service_locator.Jr97Qih', 'get_ServiceLocator_Jr97QihService.php', true],
    'App\\Controller\\ClientController::show' => ['privates', '.service_locator.G3Dsh9s', 'get_ServiceLocator_G3Dsh9sService.php', true],
    'App\\Controller\\ClientController:delete' => ['privates', '.service_locator.G3Dsh9s', 'get_ServiceLocator_G3Dsh9sService.php', true],
    'App\\Controller\\ClientController:edit' => ['privates', '.service_locator.G3Dsh9s', 'get_ServiceLocator_G3Dsh9sService.php', true],
    'App\\Controller\\ClientController:index' => ['privates', '.service_locator.Jr97Qih', 'get_ServiceLocator_Jr97QihService.php', true],
    'App\\Controller\\ClientController:show' => ['privates', '.service_locator.G3Dsh9s', 'get_ServiceLocator_G3Dsh9sService.php', true],
], [
    'App\\Controller\\ClientController::delete' => '?',
    'App\\Controller\\ClientController::edit' => '?',
    'App\\Controller\\ClientController::index' => '?',
    'App\\Controller\\ClientController::show' => '?',
    'App\\Controller\\ClientController:delete' => '?',
    'App\\Controller\\ClientController:edit' => '?',
    'App\\Controller\\ClientController:index' => '?',
    'App\\Controller\\ClientController:show' => '?',
]);
