<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3ST48Gp\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3ST48Gp/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3ST48Gp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3ST48Gp\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3ST48Gp\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3ST48Gp',
    'container.build_id' => 'fd4d4e56',
    'container.build_time' => 1572127486,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3ST48Gp');
