<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHbHe9y3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHbHe9y3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHbHe9y3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHbHe9y3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHbHe9y3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HbHe9y3',
    'container.build_id' => '8e8484a9',
    'container.build_time' => 1579198791,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHbHe9y3');
