<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MFsEwkP' shared service.

return $this->privates['.service_locator.MFsEwkP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'commande' => ['privates', '.errored..service_locator.MFsEwkP.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.MFsEwkP": it references class "App\\Entity\\Commande" but no such service exists.'],
], [
    'commande' => 'App\\Entity\\Commande',
]);
