<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.j_.vsRQ' shared service.

return $this->privates['.service_locator.j_.vsRQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CategorieController::delete' => ['privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true],
    'App\\Controller\\CategorieController::edit' => ['privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true],
    'App\\Controller\\CategorieController::index' => ['privates', '.service_locator.pPyP_uR', 'get_ServiceLocator_PPyPURService.php', true],
    'App\\Controller\\CategorieController::show' => ['privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true],
    'App\\Controller\\ClientController::delete' => ['privates', '.service_locator.G3Dsh9s', 'get_ServiceLocator_G3Dsh9sService.php', true],
    'App\\Controller\\ClientController::edit' => ['privates', '.service_locator.G3Dsh9s', 'get_ServiceLocator_G3Dsh9sService.php', true],
    'App\\Controller\\ClientController::index' => ['privates', '.service_locator.Jr97Qih', 'get_ServiceLocator_Jr97QihService.php', true],
    'App\\Controller\\ClientController::show' => ['privates', '.service_locator.G3Dsh9s', 'get_ServiceLocator_G3Dsh9sService.php', true],
    'App\\Controller\\CommandeController::delete' => ['privates', '.service_locator.MFsEwkP', 'get_ServiceLocator_MFsEwkPService.php', true],
    'App\\Controller\\CommandeController::edit' => ['privates', '.service_locator.MFsEwkP', 'get_ServiceLocator_MFsEwkPService.php', true],
    'App\\Controller\\CommandeController::index' => ['privates', '.service_locator.ZQgEv3z', 'get_ServiceLocator_ZQgEv3zService.php', true],
    'App\\Controller\\CommandeController::show' => ['privates', '.service_locator.MFsEwkP', 'get_ServiceLocator_MFsEwkPService.php', true],
    'App\\Controller\\CategorieController:delete' => ['privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true],
    'App\\Controller\\CategorieController:edit' => ['privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true],
    'App\\Controller\\CategorieController:index' => ['privates', '.service_locator.pPyP_uR', 'get_ServiceLocator_PPyPURService.php', true],
    'App\\Controller\\CategorieController:show' => ['privates', '.service_locator.DhSqxxU', 'get_ServiceLocator_DhSqxxUService.php', true],
    'App\\Controller\\ClientController:delete' => ['privates', '.service_locator.G3Dsh9s', 'get_ServiceLocator_G3Dsh9sService.php', true],
    'App\\Controller\\ClientController:edit' => ['privates', '.service_locator.G3Dsh9s', 'get_ServiceLocator_G3Dsh9sService.php', true],
    'App\\Controller\\ClientController:index' => ['privates', '.service_locator.Jr97Qih', 'get_ServiceLocator_Jr97QihService.php', true],
    'App\\Controller\\ClientController:show' => ['privates', '.service_locator.G3Dsh9s', 'get_ServiceLocator_G3Dsh9sService.php', true],
    'App\\Controller\\CommandeController:delete' => ['privates', '.service_locator.MFsEwkP', 'get_ServiceLocator_MFsEwkPService.php', true],
    'App\\Controller\\CommandeController:edit' => ['privates', '.service_locator.MFsEwkP', 'get_ServiceLocator_MFsEwkPService.php', true],
    'App\\Controller\\CommandeController:index' => ['privates', '.service_locator.ZQgEv3z', 'get_ServiceLocator_ZQgEv3zService.php', true],
    'App\\Controller\\CommandeController:show' => ['privates', '.service_locator.MFsEwkP', 'get_ServiceLocator_MFsEwkPService.php', true],
], [
    'App\\Controller\\CategorieController::delete' => '?',
    'App\\Controller\\CategorieController::edit' => '?',
    'App\\Controller\\CategorieController::index' => '?',
    'App\\Controller\\CategorieController::show' => '?',
    'App\\Controller\\ClientController::delete' => '?',
    'App\\Controller\\ClientController::edit' => '?',
    'App\\Controller\\ClientController::index' => '?',
    'App\\Controller\\ClientController::show' => '?',
    'App\\Controller\\CommandeController::delete' => '?',
    'App\\Controller\\CommandeController::edit' => '?',
    'App\\Controller\\CommandeController::index' => '?',
    'App\\Controller\\CommandeController::show' => '?',
    'App\\Controller\\CategorieController:delete' => '?',
    'App\\Controller\\CategorieController:edit' => '?',
    'App\\Controller\\CategorieController:index' => '?',
    'App\\Controller\\CategorieController:show' => '?',
    'App\\Controller\\ClientController:delete' => '?',
    'App\\Controller\\ClientController:edit' => '?',
    'App\\Controller\\ClientController:index' => '?',
    'App\\Controller\\ClientController:show' => '?',
    'App\\Controller\\CommandeController:delete' => '?',
    'App\\Controller\\CommandeController:edit' => '?',
    'App\\Controller\\CommandeController:index' => '?',
    'App\\Controller\\CommandeController:show' => '?',
]);
