<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.DhSqxxU' shared service.

return $this->privates['.service_locator.DhSqxxU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'categorie' => ['privates', '.errored..service_locator.DhSqxxU.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.DhSqxxU": it references class "App\\Entity\\Categorie" but no such service exists.'],
], [
    'categorie' => 'App\\Entity\\Categorie',
]);
