<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ZQgEv3z' shared service.

return $this->privates['.service_locator.ZQgEv3z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'commandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService.php', true],
], [
    'commandeRepository' => 'App\\Repository\\CommandeRepository',
]);
